name: PR Title Verification
on:
  pull_request:
    types:
      - synchronize
      - edited
      - opened
      - reopened
permissions: write-all
jobs:
  verify-pr-title:
    runs-on: ubuntu-22.04
    steps:
      - name: Verify PR title
        uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
