name: Release Extension
on:
  workflow_run:
    workflows:
      - 'PR Verification'
    branches:
      - 'main'
    types:
      - 'completed'
jobs:
  release-extension:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Installing yarn
        run: npm i -g yarn
      - name: Installing Project Dependencies
        run: yarn install --frozen-lockfile
      - name: Build project
        run: yarn run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
