name: PR Verification
on:
  pull_request:
    types:
      - 'synchronize'
      - 'opened'
      - 'reopened'
  push:
    branches:
      - 'dev'
      - 'main'
jobs:
  verify-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Installing yarn
        run: npm i -g yarn
      - name: Installing Project Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Lint
        run: yarn run lint
      - name: Run Format check
        run: yarn run fmt:check
      - name: Run build
        run: yarn run build
